CRITICAL - 2023-12-30 07:48:47 --> Undefined property: App\Controllers\Home::$output
#0 C:\xampp\htdocs\mi_api\app\Controllers\Home.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\Home->datos()
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-12-30 08:50:07 --> Call to a member function findAll() on null
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 08:51:02 --> Call to undefined method App\Controllers\RestPersonas::response()
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 08:55:57 --> Class "App\Models\PersonasModel" not found
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 08:56:24 --> Undefined variable $model
#0 C:\xampp\htdocs\mi_api\app\Controllers\RestPersonas.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16)
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#3 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-12-30 08:58:04 --> Class "App\Models\PersonasModel" not found
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 08:58:53 --> Call to a member function findAll() on null
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 08:59:15 --> Call to a member function findAll() on string
#0 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->index()
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-12-30 09:27:07 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-12-30 12:47:22 --> Call to undefined method App\Models\PersonasModel::create
#0 C:\xampp\htdocs\mi_api\app\Controllers\RestPersonas.php(40): CodeIgniter\Model->__call('create', Array)
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->create()
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#3 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-12-30 12:48:20 --> Call to undefined method App\Models\PersonasModel::create
#0 C:\xampp\htdocs\mi_api\app\Controllers\RestPersonas.php(40): CodeIgniter\Model->__call('create', Array)
#1 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(825): App\Controllers\RestPersonas->create()
#2 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\RestPersonas))
#3 C:\xampp\htdocs\mi_api\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\mi_api\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
